version: '3'

services:

  source:
    build:
      context: dockerfile/build-source
    environment:
      - SALESFORCE_USER=${SALESFORCE_USER}
      - SALESFORCE_PASSWORD=${SALESFORCE_PASSWORD}
      - SALESFORCE_TOKEN=${SALESFORCE_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./src/build-sorce/salesforce:/work

  dbt:
    build:
      context: dockerfile/dbt
    volumes:
      - ./:/host
      - ./profile:/root/.dbt

  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5455:5432

volumes:
  dbdata:
